import type {
  Appointment,
  Claim,
  Medication,
  ClinicalNote,
  ConsentRecord,
  Signal,
  ActivityLog,
  NotificationItem,
  UserSettings,
} from "../types/medflow";

export const initialAppointments: Appointment[] = [
  {
    id: "apt-01",
    name: "Elena Martinez",
    dob: "1984-06-12",
    phone: "+91 98201 45890",
    visit: "Follow-up · Cardiology",
    department: "Cardiology",
    provider: "Dr. Marcus Vance",
    time: "09:20",
    date: "2026-08-21",
    status: "Checked-in",
    initials: "EM",
    location: "Northstar · Suite 4B",
    insuranceVerified: true,
    consentSigned: true,
    vitalsRecorded: true,
    notes: "Patient reports mild chest tightness on exertion. ECG scheduled.",
  },
  {
    id: "apt-02",
    name: "Marcus Chen",
    dob: "1992-11-04",
    phone: "+91 94456 78901",
    visit: "New patient · Primary care",
    department: "Primary Care",
    provider: "Dr. Sarah Jenkins",
    time: "10:00",
    date: "2026-08-21",
    status: "Arriving",
    initials: "MC",
    location: "Northstar · Suite 2A",
    insuranceVerified: true,
    consentSigned: true,
    vitalsRecorded: false,
    notes: "Annual wellness check and biometric screening.",
  },
  {
    id: "apt-03",
    name: "Priya Nair",
    dob: "1978-03-29",
    phone: "+91 98123 67890",
    visit: "Medication review",
    department: "Endocrine & Diabetes" as any,
    provider: "Dr. Alan Sterling",
    time: "10:40",
    date: "2026-08-21",
    status: "In Exam",
    initials: "PN",
    location: "Northstar · Suite 3C",
    insuranceVerified: true,
    consentSigned: true,
    vitalsRecorded: true,
    notes: "HbA1c levels reassessment. Reviewing Metformin titration.",
  },
  {
    id: "apt-04",
    name: "Jonas Williams",
    dob: "1965-08-19",
    phone: "+91 97890 23456",
    visit: "Annual physical",
    department: "Primary Care",
    provider: "Dr. Sarah Jenkins",
    time: "11:20",
    date: "2026-08-21",
    status: "No-show risk",
    initials: "JW",
    location: "Northstar · Suite 1A",
    insuranceVerified: false,
    consentSigned: false,
    vitalsRecorded: false,
    notes: "SMS reminders unacknowledged. High historical cancellation rate.",
  },
  {
    id: "apt-05",
    name: "Clara Oswald",
    dob: "1990-04-15",
    phone: "+91 91234 56789",
    visit: "Pre-op Assessment",
    department: "Orthopedics",
    provider: "Dr. David Thorne",
    time: "13:00",
    date: "2026-08-21",
    status: "Confirmed",
    initials: "CO",
    location: "Northstar · Suite 5A",
    insuranceVerified: true,
    consentSigned: true,
    vitalsRecorded: false,
    notes: "Right knee arthroscopy pre-clearance and anesthesia review.",
  },
  {
    id: "apt-06",
    name: "Arthur Pendelton",
    dob: "1953-12-01",
    phone: "+91 98765 43210",
    visit: "Post-Stroke Follow-up",
    department: "Neurology",
    provider: "Dr. Rebecca Gomez",
    time: "14:15",
    date: "2026-08-21",
    status: "Confirmed",
    initials: "AP",
    location: "Northstar · Suite 2B",
    insuranceVerified: true,
    consentSigned: true,
    vitalsRecorded: false,
    notes: "Neurological exam and gait mobility evaluation.",
  },
];

export const initialClaims: Claim[] = [
  {
    id: "CLM-2841",
    patientName: "Elena Martinez",
    patientId: "PAT-1092",
    payer: "Northstar Health Payer",
    serviceDate: "2026-08-18",
    submittedDate: "2026-08-19",
    diagnosisCodes: ["I25.10", "R07.9"],
    procedureCodes: ["99214", "93000"],
    amount: 114200.0,
    expectedReimbursement: 98500.0,
    status: "Flagged Mismatch",
    flagReason: "Payer adjudication formula differs by 14% from agreed fee schedule.",
    notes: "Automated appeal letter generated for contract clause 4.2 compliance.",
  },
  {
    id: "CLM-2818",
    patientName: "Marcus Chen",
    patientId: "PAT-1104",
    payer: "Horizon Blue",
    serviceDate: "2026-08-15",
    submittedDate: "2026-08-16",
    diagnosisCodes: ["Z00.00", "E78.5"],
    procedureCodes: ["99395", "80061"],
    amount: 54800.0,
    expectedReimbursement: 47500.0,
    status: "Under Review",
    notes: "Routine preventative package under standard 14-day cycle.",
  },
  {
    id: "CLM-2794",
    patientName: "Priya Nair",
    patientId: "PAT-0988",
    payer: "Aetna Medicare",
    serviceDate: "2026-08-10",
    submittedDate: "2026-08-11",
    diagnosisCodes: ["E11.9", "Z79.4"],
    procedureCodes: ["99213", "83036"],
    amount: 36500.0,
    expectedReimbursement: 32000.0,
    status: "Approved",
    notes: "Approved for direct NEFT/RTGS settlement on 2026-08-25.",
  },
  {
    id: "CLM-2750",
    patientName: "Harold Sterling",
    patientId: "PAT-0854",
    payer: "UnitedHealthcare",
    serviceDate: "2026-08-05",
    submittedDate: "2026-08-06",
    diagnosisCodes: ["M17.11"],
    procedureCodes: ["20610", "73562"],
    amount: 232000.0,
    expectedReimbursement: 198000.0,
    status: "Paid",
    notes: "Full payment received and posted to hospital ledger.",
  },
  {
    id: "CLM-2733",
    patientName: "David Zhao",
    patientId: "PAT-0791",
    payer: "Medicaid Direct",
    serviceDate: "2026-08-01",
    submittedDate: "2026-08-02",
    diagnosisCodes: ["J45.909"],
    procedureCodes: ["94010", "99213"],
    amount: 31000.0,
    expectedReimbursement: 25500.0,
    status: "Clean / Ready",
    notes: "Prior cashless authorization attached and verified.",
  },
];

export const initialMedications: Medication[] = [
  {
    id: "MED-01",
    name: "Amoxicillin",
    genericName: "Amoxicillin Trihydrate",
    dosage: "500mg Capsules",
    category: "Antibiotics",
    stock: 42,
    unit: "bottles (100ct)",
    reorderThreshold: 50,
    unitCost: 1480.0,
    expiryDate: "2027-04-30",
    location: "Main Pharmacy · Shelf A-12",
    status: "Low Stock",
    batchNumber: "LOT-9921A",
  },
  {
    id: "MED-02",
    name: "Metformin HCl",
    genericName: "Metformin Hydrochloride",
    dosage: "850mg Tablets",
    category: "Endocrine & Diabetes",
    stock: 180,
    unit: "bottles (100ct)",
    reorderThreshold: 60,
    unitCost: 980.0,
    expiryDate: "2027-09-15",
    location: "Main Pharmacy · Shelf C-04",
    status: "In Stock",
    batchNumber: "LOT-8840B",
  },
  {
    id: "MED-03",
    name: "Ceftriaxone",
    genericName: "Ceftriaxone Sodium",
    dosage: "1g IV Vial",
    category: "Antibiotics",
    stock: 28,
    unit: "vials",
    reorderThreshold: 30,
    unitCost: 3600.0,
    expiryDate: "2026-11-30",
    location: "Refrigerated Vault · R-2",
    status: "Low Stock",
    batchNumber: "LOT-7719C",
  },
  {
    id: "MED-04",
    name: "Epinephrine Auto-Injector",
    genericName: "Epinephrine",
    dosage: "0.3mg 2-Pak",
    category: "Emergency & Critical",
    stock: 14,
    unit: "packs",
    reorderThreshold: 15,
    unitCost: 11600.0,
    expiryDate: "2027-01-20",
    location: "Emergency Cart · EC-1",
    status: "Critical Low",
    batchNumber: "LOT-6643E",
  },
  {
    id: "MED-05",
    name: "Atorvastatin Calcium",
    genericName: "Atorvastatin",
    dosage: "20mg Tablets",
    category: "Cardiology",
    stock: 240,
    unit: "bottles (90ct)",
    reorderThreshold: 80,
    unitCost: 1820.0,
    expiryDate: "2028-02-14",
    location: "Main Pharmacy · Shelf B-08",
    status: "In Stock",
    batchNumber: "LOT-5512A",
  },
  {
    id: "MED-06",
    name: "Albuterol HFA",
    genericName: "Albuterol Sulfate",
    dosage: "90mcg Inhaler",
    category: "Respiratory",
    stock: 85,
    unit: "canisters",
    reorderThreshold: 40,
    unitCost: 2720.0,
    expiryDate: "2027-07-01",
    location: "Main Pharmacy · Shelf D-01",
    status: "In Stock",
    batchNumber: "LOT-4419R",
  },
];

export const initialClinicalNotes: ClinicalNote[] = [
  {
    id: "NOTE-101",
    patientName: "Elena Martinez",
    patientId: "PAT-1092",
    provider: "Dr. Marcus Vance",
    type: "SOAP Note",
    date: "2026-08-21",
    subjective: "Patient reports 2-week history of exertional dyspnea and intermittent left-sided chest tightness. Relieved with rest within 5 minutes.",
    objective: "BP 138/84 mmHg, HR 76 bpm regular. Cardiovascular: S1/S2 present, no murmurs or gallops. Lungs clear to auscultation bilaterally.",
    assessment: "Atypical angina pectoris vs stable coronary artery disease. Essential hypertension well controlled.",
    plan: "1. Resting ECG and order outpatient nuclear stress test.\n2. Add low-dose Aspirin 81mg daily.\n3. Return to clinic in 3 weeks with test results.",
    qualityScore: 98,
    status: "Pending Attending Review",
  },
  {
    id: "NOTE-102",
    patientName: "Marcus Chen",
    patientId: "PAT-1104",
    provider: "Dr. Sarah Jenkins",
    type: "Progress Note",
    date: "2026-08-20",
    subjective: "Annual checkup. No acute complaints. Maintains active lifestyle, runs 3x weekly.",
    objective: "BP 118/74 mmHg, BMI 22.4. Comprehensive metabolic panel within normal limits. Lipid panel: Total Chol 182, LDL 104, HDL 58.",
    assessment: "Healthy adult male with excellent cardiovascular risk profile.",
    plan: "Routine follow-up in 12 months. Encouraged dietary fiber intake.",
    qualityScore: 100,
    status: "Signed & Finalized",
  },
  {
    id: "NOTE-103",
    patientName: "Harold Sterling",
    patientId: "PAT-0854",
    provider: "Dr. David Thorne",
    type: "Operative Summary",
    date: "2026-08-19",
    subjective: "Patient presented with severe right knee osteoarthritis failing conservative management.",
    objective: "Right knee arthrocentesis and intra-articular corticosteroid injection performed under sterile technique with ultrasound guidance.",
    assessment: "Osteoarthritis of right knee, tricompartmental.",
    plan: "Cryotherapy, avoid strenuous weight-bearing for 48 hours. Physical therapy prescription renewed.",
    qualityScore: 96,
    status: "Signed & Finalized",
  },
  {
    id: "NOTE-104",
    patientName: "Arthur Pendelton",
    patientId: "PAT-0731",
    provider: "Dr. Rebecca Gomez",
    type: "Discharge Summary",
    date: "2026-08-17",
    subjective: "Post-ischemic stroke day 5 recovery. Speech clarity improved, right arm strength 4+/5.",
    objective: "NIHSS score improved from 8 on admission to 2. Carotid Doppler: 40% stenosis right ICA.",
    assessment: "Acute ischemic stroke with rapid neurological resolution. Good functional recovery.",
    plan: "Discharged home with outpatient physical & occupational therapy. Clopidogrel 75mg daily.",
    qualityScore: 94,
    status: "Signed & Finalized",
  },
];

export const initialConsentRecords: ConsentRecord[] = [
  {
    id: "CNS-01",
    patientName: "Elena Martinez",
    patientId: "PAT-1092",
    documentType: "General Treatment Consent",
    signedDate: "2026-08-21",
    expiryDate: "2027-08-21",
    witnessProvider: "Nurse Jessica Blair, RN",
    status: "Compliant",
    notes: "Signed digitally at front desk kiosk.",
  },
  {
    id: "CNS-02",
    patientName: "Clara Oswald",
    patientId: "PAT-1118",
    documentType: "Surgical & Invasive Procedure Consent",
    signedDate: "2026-08-20",
    expiryDate: "2026-09-20",
    witnessProvider: "Dr. David Thorne",
    status: "Compliant",
    notes: "Informed consent for right knee arthroscopy.",
  },
  {
    id: "CNS-03",
    patientName: "Jonas Williams",
    patientId: "PAT-0672",
    documentType: "HIPAA Privacy Notice Acknowledgement",
    signedDate: "2025-07-14",
    expiryDate: "2026-07-14",
    witnessProvider: "Reception Desk",
    status: "Expired",
    notes: "Annual renewal required upon check-in.",
  },
  {
    id: "CNS-04",
    patientName: "Arthur Pendelton",
    patientId: "PAT-0731",
    documentType: "Telehealth Services Disclosure",
    signedDate: "2026-03-10",
    expiryDate: "2027-03-10",
    witnessProvider: "Dr. Rebecca Gomez",
    status: "Compliant",
    notes: "Covers remote stroke follow-up telehealth consultations.",
  },
  {
    id: "CNS-05",
    patientName: "David Zhao",
    patientId: "PAT-0791",
    documentType: "General Treatment Consent",
    signedDate: "2026-08-01",
    expiryDate: "2027-08-01",
    witnessProvider: "Reception Desk",
    status: "Compliant",
    notes: "Electronic signature verified.",
  },
];

export const initialSignals: Signal[] = [
  {
    id: "sig-01",
    title: "4 appointments may become no-shows",
    detail: "Automated SMS reminder cadence queued for the 11:20–13:00 intake window.",
    category: "Front",
    tone: "amber",
    severity: "High",
    status: "open",
    timestamp: "10 min ago",
    recommendedAction: "Trigger 2-way priority SMS confirmation to unconfirmed patients",
    impact: "Estimated recovery of ₹34,000 in scheduled provider clinical time",
  },
  {
    id: "sig-02",
    title: "Amoxicillin reorder threshold reached",
    detail: "Current stock is 42 units. Predicted depletion within 72 hours based on dispensing velocity.",
    category: "Pharmacy",
    tone: "green",
    severity: "Medium",
    status: "open",
    timestamp: "24 min ago",
    recommendedAction: "Dispatch automated PO-892 to Northstar Medical Supply for 100 units",
    impact: "Prevents treatment delay for approximately 35 pediatric and adult patients",
  },
  {
    id: "sig-03",
    title: "Cardiology referrals have no visit scheduled after 14 days",
    detail: "Three patient referrals from primary care are awaiting first appointment booking.",
    category: "Clinical",
    tone: "rose",
    severity: "Critical",
    status: "open",
    timestamp: "45 min ago",
    recommendedAction: "Auto-assign outreach queue to Care Coordinator Emily Watson",
    impact: "Reduces clinical risk for high-priority cardiology follow-ups",
  },
  {
    id: "sig-04",
    title: "Claim CLM-2841 rate discrepancy",
    detail: "Northstar Health Payer adjudicated claim with a 14% variance against current contracted rate schedule.",
    category: "Billing",
    tone: "blue",
    severity: "High",
    status: "open",
    timestamp: "1 hour ago",
    recommendedAction: "Submit auto-drafted contractual appeal with fee schedule Exhibit B",
    impact: "Protects ₹21,600 in underpaid reimbursement",
  },
];

export const initialActivity: ActivityLog[] = [
  {
    id: "act-01",
    title: "Claim CLM-2841 flagged for payer rate review",
    actor: "Billing Bot · Auto-Audit",
    timestamp: "2 min ago",
    tone: "amber",
    module: "Billing",
  },
  {
    id: "act-02",
    title: "Consent form completed · Elena Martinez",
    actor: "Front Desk · Kiosk 2",
    timestamp: "14 min ago",
    tone: "green",
    module: "Front",
  },
  {
    id: "act-03",
    title: "Reorder request generated · Amoxicillin 500mg",
    actor: "Pharmacy Bot · Inventory Guard",
    timestamp: "28 min ago",
    tone: "blue",
    module: "Pharmacy",
  },
  {
    id: "act-04",
    title: "Referral intake flag triggered · Cardiology",
    actor: "Insight Bot · Care Continuity",
    timestamp: "41 min ago",
    tone: "rose",
    module: "Insight",
  },
  {
    id: "act-05",
    title: "Clinical note signed · Dr. Sarah Jenkins",
    actor: "EHR Scribe Bridge",
    timestamp: "1 hour ago",
    tone: "green",
    module: "Clinical",
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: "notif-01",
    message: "Claim CLM-2841 was flagged for contract rate discrepancy.",
    timestamp: "2 min ago",
    read: false,
    type: "warning",
    targetModule: "Billing",
  },
  {
    id: "notif-02",
    message: "Consent form successfully signed for Elena Martinez.",
    timestamp: "14 min ago",
    read: false,
    type: "success",
    targetModule: "Front",
  },
  {
    id: "notif-03",
    message: "Amoxicillin stock (42 units) reached automatic reorder trigger.",
    timestamp: "28 min ago",
    read: false,
    type: "alert",
    targetModule: "Pharmacy",
  },
  {
    id: "notif-04",
    message: "Compliance audit scan passed with 96.8% overall score.",
    timestamp: "2 hours ago",
    read: true,
    type: "info",
    targetModule: "Compliance",
  },
];

export const defaultSettings: UserSettings = {
  facilityName: "Northstar Health Network",
  operatorName: "Avery Thomas",
  operatorRole: "Operations Lead",
  theme: "light",
  autoAuditIntervalHours: 4,
  enableAiAnomalyDetection: true,
  lowStockThresholdPercent: 20,
  noShowWarningThresholdHours: 2,
  emailNotifications: true,
  soundAlerts: false,
};
